### ISSUE TITLE
Standings Object is wrong

### ISSUE THREAD

**Issue by AlexHawkins1** [SwapnikKatkoori/sleeper-ff-bot#8]
My Edit to the api-wrapper made the standings object wrong. 

line 412 should be changed:
-  string_to_add = "{0:^7} {1:^10} {2:>7} {3:>7}\n".format(i + 1, team_name, standing[1], standing[2])
+ string_to_add = "{0:^7} {1:^10} {2:>7} {3:>7}\n".format(i + 1, team_name, standing[1], standing[3])

Sorry I missed this.

**Comment by SwapnikKatkoori** [comment]
@AlexHawkins1 Good catch. I think it should(?) be good for now because its still using v1.0.2 of the sleeper wrapper, but i'm going to leave this up as a reminder to change this line when I update to the newest version.

**Comment by SwapnikKatkoori** [comment]
Fixed in the latest version.
